### ISSUE TITLE
test is throwing errors -  "before each" hook for "flashswap should work correctly"

### ISSUE THREAD

**Issue by secp600k1** [carlosalv098/flashswap_uniswap#1]
First of all, thank you for posting the repo. I tried deploying on ropsten and it went well. But when I tried 'hardhat test', the test throws an error like this:
```
 Flashswap_Uniswap
    1) "before each" hook for "flashswap should work correctly"


  0 passing (167ms)
  1 failing

  1) Flashswap_Uniswap
       "before each" hook for "flashswap should work correctly":
     Error: call revert exception (method="balanceOf(address)", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.4.0)
      at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:213:28)
      at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:225:20)
      at Interface.decodeFunctionResult (node_modules/@ethersproject/abi/src.ts/interface.ts:425:23)
      at Contract.<anonymous> (node_modules/@ethersproject/contracts/src.ts/index.ts:332:44)
      at step (node_modules/@ethersproject/contracts/lib/index.js:48:23)
      at Object.next (node_modules/@ethersproject/contracts/lib/index.js:29:53)
      at fulfilled (node_modules/@ethersproject/contracts/lib/index.js:20:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:528:9)
```

To add: I inserted addresses directly rather than .env for test purpose. Also, can you tell me what you exactly meant by 'DAI_WHALE' const. I took DAI ropsten address. Please correct me if am wrong.
Thank you

**Comment by carlosalv098** [comment]
Hi @0xPlask to run this test you need to have a DAI_WHALE which is an address on mainnet that has a lot of DAI, you can find it on etherscan, you also need to add an RPC node for mainnet in hardhat.config

The test will be running on a mainnet fork
